In [3]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [4]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
], dtype="float32")

y = np.array([0, 0, 0, 1], dtype="float32")

In [5]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [6]:
y

array([0., 0., 0., 1.], dtype=float32)

In [7]:
model = Sequential()

In [8]:
model.add(Dense(1, input_dim=2, activation="sigmoid"))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [10]:
model.summary() # 현재 sequential의 레이어를 보여준다 // param 은 전체 웨이트 값과 마지막 하나의 바이어스값 수의 ㅎ합....

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc']) # acc정확도로 분석할 것이다

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [12]:
model.fit(X, y, epochs=100)


Epoch 1/100
4/4 [==============================] - 0s 50ms/step - loss: 0.7534 - acc: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 497us/step - loss: 0.7228 - acc: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 500us/step - loss: 0.6933 - acc: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 249us/step - loss: 0.6651 - acc: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 500us/step - loss: 0.6380 - acc: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 248us/step - loss: 0.6122 - acc: 0.7500
Epoch 7/100
4/4 [==============================] - 0s 499us/step - loss: 0.5876 - acc: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 249us/step - loss: 0.5643 - acc: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 250us/step - loss: 0.5421 - acc: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 252us/step - loss: 0.5212 - acc: 0.7500
Epoch 11/100
4/4 [==============================] - 0s 500u

Epoch 86/100
4/4 [==============================] - 0s 250us/step - loss: 0.1010 - acc: 1.0000
Epoch 87/100
4/4 [==============================] - 0s 252us/step - loss: 0.0997 - acc: 1.0000
Epoch 88/100
4/4 [==============================] - 0s 250us/step - loss: 0.0985 - acc: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 0us/step - loss: 0.0973 - acc: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 0us/step - loss: 0.0961 - acc: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 250us/step - loss: 0.0949 - acc: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 250us/step - loss: 0.0938 - acc: 1.0000
Epoch 93/100
4/4 [==============================] - 0s 250us/step - loss: 0.0927 - acc: 1.0000
Epoch 94/100
4/4 [==============================] - 0s 250us/step - loss: 0.0916 - acc: 1.0000
Epoch 95/100
4/4 [==============================] - 0s 250us/step - loss: 0.0905 - acc: 1.0000
Epoch 96/100
4/4 [==============================] - 0s

In [13]:
pred = model.predict(X)
pred

array([[0.00162624],
       [0.10616067],
       [0.09071023],
       [0.87913805]], dtype=float32)

In [ ]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

In [ ]:
predict02 = predict01.flatten()
predict02

In [ ]:
predict03 = (predict02 == y)
predict03

In [ ]:
np.sum(predict03)

In [ ]:
acc = np.sum(predict03) / 4
acc

In [ ]:
arr=np.array([[0,1]], dtype="float32")
pred = model.predict(arr)
pred

In [ ]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

In [ ]:
arr=np.array([[1,1]], dtype="float32")
pred = model.predict(arr)
pred

In [ ]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)