In [1]:
# 활성화 함수를 직접 만들어보자

In [2]:
import numpy as np

In [3]:
x = np.array([-1.0, 1.0, 2.0])
x

array([-1.,  1.,  2.])

In [4]:
# 활성함수
y = x > 0

In [5]:
y

array([False,  True,  True])

In [6]:
y = y.astype(np.int)
y

array([0, 1, 1])