In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.nn import relu
from sklearn import datasets
from sklearn.model_selection import train_test_split
tf.enable_eager_execution()

In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
X = np.array(X, dtype="float32")
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [5]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
y = np.array(y, dtype="float32")
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [7]:
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
X_train

array([[1.706e+01, 2.100e+01, 1.118e+02, ..., 1.827e-01, 2.623e-01,
        7.599e-02],
       [2.073e+01, 3.112e+01, 1.357e+02, ..., 1.659e-01, 2.868e-01,
        8.218e-02],
       [1.374e+01, 1.791e+01, 8.812e+01, ..., 6.019e-02, 2.350e-01,
        7.014e-02],
       ...,
       [1.476e+01, 1.474e+01, 9.487e+01, ..., 1.251e-01, 3.109e-01,
        8.187e-02],
       [1.086e+01, 2.148e+01, 6.851e+01, ..., 0.000e+00, 2.458e-01,
        6.592e-02],
       [1.218e+01, 1.408e+01, 7.725e+01, ..., 1.852e-02, 2.293e-01,
        6.037e-02]], dtype=float32)

In [10]:
X_test

array([[9.738e+00, 1.197e+01, 6.124e+01, ..., 0.000e+00, 3.105e-01,
        8.151e-02],
       [1.573e+01, 1.128e+01, 1.028e+02, ..., 1.452e-01, 2.557e-01,
        8.181e-02],
       [1.189e+01, 1.835e+01, 7.732e+01, ..., 1.138e-01, 3.397e-01,
        8.365e-02],
       ...,
       [1.291e+01, 1.633e+01, 8.253e+01, ..., 8.235e-02, 3.024e-01,
        6.949e-02],
       [1.505e+01, 1.907e+01, 9.726e+01, ..., 1.120e-01, 2.282e-01,
        6.954e-02],
       [1.321e+01, 2.806e+01, 8.488e+01, ..., 7.958e-02, 2.473e-01,
        6.443e-02]], dtype=float32)

In [11]:
y_train

array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],

In [12]:
y_test

array([[1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
X_train = scaler.transform(X_train)
X_train

array([[ 0.8452182 ,  0.34657267,  0.82675767, ...,  1.0118    ,
        -0.47634298, -0.45490235],
       [ 1.895105  ,  2.6676092 ,  1.8169273 , ...,  0.76073414,
        -0.07534674, -0.11676123],
       [-0.10454296, -0.36212325, -0.15429777, ..., -0.81903994,
        -0.9231679 , -0.7744703 ],
       ...,
       [ 0.1872513 , -1.0891672 ,  0.12535274, ...,  0.15100196,
         0.31910297, -0.1336958 ],
       [-0.9284323 ,  0.45666125, -0.96673435, ..., -1.7185442 ,
        -0.746402  , -1.004996  ],
       [-0.5508162 , -1.2405392 , -0.6046388 , ..., -1.4417735 ,
        -1.0164608 , -1.3081759 ]], dtype=float32)

In [15]:
initializer = tf.contrib.layers.xavier_initializer()
w = tf.Variable(initializer([30, 1]))
w

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[ 0.04140279],
       [-0.25259668],
       [ 0.3421672 ],
       [ 0.2763911 ],
       [-0.12660539],
       [ 0.25393873],
       [ 0.38634217],
       [ 0.10256529],
       [ 0.20728296],
       [ 0.12826622],
       [-0.06586716],
       [ 0.23994017],
       [ 0.29372424],
       [ 0.22123408],
       [ 0.27886033],
       [ 0.37141293],
       [ 0.16367674],
       [-0.06609109],
       [-0.12880653],
       [ 0.01296464],
       [-0.3929586 ],
       [ 0.26498502],
       [ 0.2623908 ],
       [-0.12965664],
       [ 0.35109514],
       [ 0.29095596],
       [ 0.3949595 ],
       [-0.14973503],
       [-0.39977092],
       [ 0.27991343]], dtype=float32)>

In [16]:
b = tf.Variable(initializer([1]))
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.092754], dtype=float32)>

In [17]:
tf.matmul(X_train, w) + b

<tf.Tensor: id=35, shape=(455, 1), dtype=float32, numpy=
array([[ 2.85674286e+00],
       [ 3.07561898e+00],
       [-1.47585428e+00],
       [-1.57886207e+00],
       [-2.08417559e+00],
       [ 1.07858253e+00],
       [ 3.08004713e+00],
       [-2.28427410e-01],
       [ 5.24430561e+00],
       [-9.36612964e-01],
       [ 1.37028420e+00],
       [ 2.17369509e+00],
       [ 1.12785339e+00],
       [ 6.36163616e+00],
       [-2.29442120e+00],
       [-4.22189116e-01],
       [-2.92821455e+00],
       [-7.55998969e-01],
       [-9.60788608e-01],
       [ 4.07357156e-01],
       [ 9.72498059e-02],
       [-1.06054509e+00],
       [ 1.06422353e+00],
       [ 5.60645223e-01],
       [ 3.65505278e-01],
       [-1.96284235e+00],
       [ 4.86572266e+00],
       [-1.17986691e+00],
       [ 3.45638418e+00],
       [-1.46337354e+00],
       [ 2.12041569e+00],
       [ 1.08865166e+00],
       [ 1.66374958e+00],
       [-2.55023360e-01],
       [ 2.34817028e+00],
       [ 8.99460411e+00],
       

In [18]:
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
hypothesis

<tf.Tensor: id=41, shape=(455, 1), dtype=float32, numpy=
array([[0.94566613],
       [0.9558759 ],
       [0.18605444],
       [0.1709567 ],
       [0.1106444 ],
       [0.74622566],
       [0.9560622 ],
       [0.44314018],
       [0.9947502 ],
       [0.28158504],
       [0.7974261 ],
       [0.8978623 ],
       [0.7554425 ],
       [0.9982765 ],
       [0.09158602],
       [0.39599305],
       [0.05077633],
       [0.3195156 ],
       [0.27672035],
       [0.600454  ],
       [0.5242933 ],
       [0.2572053 ],
       [0.74349684],
       [0.6366018 ],
       [0.59037244],
       [0.12315977],
       [0.9923527 ],
       [0.23507613],
       [0.9694209 ],
       [0.1879519 ],
       [0.8928717 ],
       [0.74812776],
       [0.8407407 ],
       [0.43658748],
       [0.9127887 ],
       [0.9998759 ],
       [0.92656654],
       [0.7848297 ],
       [0.99594045],
       [0.45102862],
       [0.90945184],
       [0.86689043],
       [0.7449467 ],
       [0.30879548],
       [0.6727884 ]

In [19]:
optimizer = tf.train.AdamOptimizer(0.001)

In [20]:
for step in range(5000):
    with tf.GradientTape() as tape:
        hypotesis = tf.sigmoid(tf.matmul(X_train, w) + b)
        cost = -tf.reduce_mean(y_train * tf.log(hypotesis) + (1 - y_train) * tf.log(1 - hypothesis))
        grads = tape.gradient(cost, [w, b])
    optimizer.apply_gradients(grads_and_vars=zip(grads, [w, b]))
    
    if step % 10 == 0:
        print("=" * 50)
        print("step: {}, cost: {}, w: {}, b: {}".format(step, cost.numpy(), w.numpy(), b.numpy()))
        print("=" * 50)

step: 0, cost: 1.8581620454788208, w: [[ 0.04040279]
 [-0.25359666]
 [ 0.3411672 ]
 [ 0.2753911 ]
 [-0.1276054 ]
 [ 0.25293875]
 [ 0.38534218]
 [ 0.10156529]
 [ 0.20628296]
 [ 0.12726621]
 [-0.06686716]
 [ 0.23894018]
 [ 0.29272425]
 [ 0.22023408]
 [ 0.27786034]
 [ 0.37041295]
 [ 0.16267674]
 [-0.06709109]
 [-0.12980647]
 [ 0.01196464]
 [-0.3939586 ]
 [ 0.26398504]
 [ 0.2613908 ]
 [-0.13065664]
 [ 0.35009515]
 [ 0.28995597]
 [ 0.39395952]
 [-0.15073504]
 [-0.4007709 ]
 [ 0.27891344]], b: [1.093754]
step: 10, cost: 1.805234670639038, w: [[ 0.03042255]
 [-0.263573  ]
 [ 0.33118683]
 [ 0.2654105 ]
 [-0.13758683]
 [ 0.24295767]
 [ 0.3753609 ]
 [ 0.09158443]
 [ 0.1963066 ]
 [ 0.11728326]
 [-0.07684711]
 [ 0.22896169]
 [ 0.28274426]
 [ 0.21025352]
 [ 0.26787525]
 [ 0.36043158]
 [ 0.15269507]
 [-0.0770713 ]
 [-0.13959856]
 [ 0.00198374]
 [-0.40393922]
 [ 0.25400612]
 [ 0.25141016]
 [-0.14063749]
 [ 0.34011108]
 [ 0.27997407]
 [ 0.38397753]
 [-0.16071633]
 [-0.41074824]
 [ 0.26893058]], b: [1.

step: 200, cost: 1.366770625114441, w: [[-0.10819545]
 [-0.39139277]
 [ 0.19275068]
 [ 0.12547119]
 [-0.26639724]
 [ 0.10838123]
 [ 0.2369831 ]
 [-0.04599633]
 [ 0.07236156]
 [-0.01337232]
 [-0.2157471 ]
 [ 0.09107545]
 [ 0.14427736]
 [ 0.06957173]
 [ 0.12932105]
 [ 0.22700866]
 [ 0.01813305]
 [-0.20774879]
 [-0.00604335]
 [-0.12888235]
 [-0.5433444 ]
 [ 0.12220956]
 [ 0.11230162]
 [-0.28137574]
 [ 0.20446093]
 [ 0.14356394]
 [ 0.24602966]
 [-0.2968351 ]
 [-0.5395958 ]
 [ 0.13267788]], b: [1.2475474]
step: 210, cost: 1.3608752489089966, w: [[-0.11294069]
 [-0.39515096]
 [ 0.18803914]
 [ 0.1205821 ]
 [-0.26978788]
 [ 0.10426389]
 [ 0.23240396]
 [-0.05053457]
 [ 0.06924765]
 [-0.01665585]
 [-0.22049466]
 [ 0.08689616]
 [ 0.13958435]
 [ 0.06461263]
 [ 0.12510139]
 [ 0.22313954]
 [ 0.01419996]
 [-0.21136114]
 [ 0.00213263]
 [-0.13227579]
 [-0.54817057]
 [ 0.11812102]
 [ 0.10752228]
 [-0.28634948]
 [ 0.2003122 ]
 [ 0.13924563]
 [ 0.241528  ]
 [-0.30117896]
 [-0.5433895 ]
 [ 0.12848906]], b:

step: 400, cost: 1.3071175813674927, w: [[-0.18326281]
 [-0.44723338]
 [ 0.11870465]
 [ 0.04684701]
 [-0.30715227]
 [ 0.05168192]
 [ 0.16976172]
 [-0.11439403]
 [ 0.03674435]
 [-0.04023628]
 [-0.28966665]
 [ 0.04132004]
 [ 0.07133042]
 [-0.01040298]
 [ 0.07061819]
 [ 0.18054506]
 [-0.02372841]
 [-0.24761353]
 [ 0.12712699]
 [-0.15394686]
 [-0.6205441 ]
 [ 0.05913936]
 [ 0.03644291]
 [-0.36224827]
 [ 0.14420359]
 [ 0.08145118]
 [ 0.1802834 ]
 [-0.36040175]
 [-0.5955232 ]
 [ 0.07610475]], b: [1.3371311]
step: 410, cost: 1.3057100772857666, w: [[-0.1862794 ]
 [-0.44936743]
 [ 0.11575013]
 [ 0.04362204]
 [-0.30827603]
 [ 0.0497832 ]
 [ 0.16731864]
 [-0.11699516]
 [ 0.03586847]
 [-0.04015402]
 [-0.2926002 ]
 [ 0.04004142]
 [ 0.06843572]
 [-0.0137091 ]
 [ 0.06843454]
 [ 0.17938428]
 [-0.02432489]
 [-0.24836498]
 [ 0.13185875]
 [-0.15349084]
 [-0.6236942 ]
 [ 0.05662367]
 [ 0.03337385]
 [-0.36561382]
 [ 0.14195381]
 [ 0.07923352]
 [ 0.17790431]
 [-0.36272493]
 [-0.5976506 ]
 [ 0.07427157]], b

step: 610, cost: 1.2867435216903687, w: [[-0.2383868 ]
 [-0.48514286]
 [ 0.06488496]
 [-0.01313455]
 [-0.3233512 ]
 [ 0.02061928]
 [ 0.12712447]
 [-0.16092907]
 [ 0.02517187]
 [-0.02890025]
 [-0.34402284]
 [ 0.02257554]
 [ 0.01783785]
 [-0.07291725]
 [ 0.02734534]
 [ 0.16635267]
 [-0.02328485]
 [-0.25234926]
 [ 0.18862474]
 [-0.13078496]
 [-0.6789582 ]
 [ 0.01296829]
 [-0.02019353]
 [-0.42565817]
 [ 0.10350867]
 [ 0.04359548]
 [ 0.13904741]
 [-0.40069002]
 [-0.6338495 ]
 [ 0.04623088]], b: [1.4127187]
step: 620, cost: 1.2860887050628662, w: [[-0.24065956]
 [-0.48664704]
 [ 0.06267186]
 [-0.01566114]
 [-0.32384998]
 [ 0.01948022]
 [ 0.12541792]
 [-0.16282198]
 [ 0.02485378]
 [-0.02811144]
 [-0.3463258 ]
 [ 0.02191374]
 [ 0.01558399]
 [-0.07561148]
 [ 0.02532838]
 [ 0.16603552]
 [-0.02285961]
 [-0.25219148]
 [ 0.18992865]
 [-0.12928902]
 [-0.6814111 ]
 [ 0.01105693]
 [-0.02256026]
 [-0.42837042]
 [ 0.10182416]
 [ 0.04213842]
 [ 0.13741569]
 [-0.40227023]
 [-0.6354107 ]
 [ 0.04511506]], b

step: 810, cost: 1.2764273881912231, w: [[-0.27946424]
 [-0.51134527]
 [ 0.02492951]
 [-0.05959494]
 [-0.3306069 ]
 [ 0.00142581]
 [ 0.09608082]
 [-0.19517478]
 [ 0.02074298]
 [-0.01303128]
 [-0.38693562]
 [ 0.01029981]
 [-0.02386004]
 [-0.12348274]
 [-0.01288509]
 [ 0.16302985]
 [-0.01301471]
 [-0.24622396]
 [ 0.19926798]
 [-0.09977747]
 [-0.7239729 ]
 [-0.02164638]
 [-0.06349576]
 [-0.47614154]
 [ 0.07257   ]
 [ 0.01825804]
 [ 0.10969457]
 [-0.42858043]
 [-0.6618645 ]
 [ 0.02655942]], b: [1.4766992]
step: 820, cost: 1.2760310173034668, w: [[-2.8130686e-01]
 [-5.1246649e-01]
 [ 2.3139104e-02]
 [-6.1721817e-02]
 [-3.3084568e-01]
 [ 6.3134584e-04]
 [ 9.4663635e-02]
 [-1.9671784e-01]
 [ 2.0603202e-02]
 [-1.2274855e-02]
 [-3.8893387e-01]
 [ 9.7111389e-03]
 [-2.5784105e-02]
 [-1.2585278e-01]
 [-1.4881695e-02]
 [ 1.6298984e-01]
 [-1.2468975e-02]
 [-2.4580149e-01]
 [ 1.9921260e-01]
 [-9.8231882e-02]
 [-7.2602922e-01]
 [-2.3203237e-02]
 [-6.5467283e-02]
 [-4.7848505e-01]
 [ 7.1151488e-02]
 [ 

step: 1030, cost: 1.2693425416946411, w: [[-0.31641796]
 [-0.5328125 ]
 [-0.01094851]
 [-0.10306744]
 [-0.3338897 ]
 [-0.01340075]
 [ 0.06687078]
 [-0.22635315]
 [ 0.01882443]
 [ 0.00207428]
 [-0.42849016]
 [-0.00255163]
 [-0.06348305]
 [-0.17297609]
 [-0.05600439]
 [ 0.16387278]
 [-0.00174919]
 [-0.23558693]
 [ 0.19305147]
 [-0.06719324]
 [-0.7659338 ]
 [-0.05300449]
 [-0.10360968]
 [-0.5246581 ]
 [ 0.04345385]
 [-0.00284512]
 [ 0.08275139]
 [-0.4527437 ]
 [-0.686713  ]
 [ 0.00888351]], b: [1.541467]
step: 1040, cost: 1.2690861225128174, w: [[-0.31793997]
 [-0.5336488 ]
 [-0.01242485]
 [-0.10489763]
 [-0.33395344]
 [-0.01395928]
 [ 0.06562554]
 [-0.22764954]
 [ 0.01878586]
 [ 0.00268252]
 [-0.43027392]
 [-0.00313184]
 [-0.06516477]
 [-0.17510979]
 [-0.05791467]
 [ 0.16398238]
 [-0.00128735]
 [-0.23505242]
 [ 0.19263288]
 [-0.06579216]
 [-0.7676973 ]
 [-0.0543046 ]
 [-0.10529002]
 [-0.52673024]
 [ 0.04222137]
 [-0.00367927]
 [ 0.08161691]
 [-0.45372406]
 [-0.6877303 ]
 [ 0.0081423 ]], 

step: 1250, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1260, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1270, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1280, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1290, 

step: 1580, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1590, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1600, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1610, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1620, 

step: 1900, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1910, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1920, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1930, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 1940, 

step: 2210, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2220, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2230, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2240, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2250, 

step: 2540, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2550, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2560, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2570, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2580, 

step: 2850, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2860, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2870, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2880, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 2890, 

step: 3160, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3170, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3180, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3190, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3200, 

step: 3480, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3490, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3500, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3510, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3520, 

step: 3770, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3780, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3790, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3800, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 3810, 

step: 4100, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4110, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4120, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4130, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4140, 

step: 4410, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4420, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4430, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4440, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4450, 

step: 4720, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4730, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4740, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4750, cost: nan, w: [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]], b: [nan]
step: 4760, 

In [21]:
w

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)>

In [22]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([nan], dtype=float32)>

In [23]:
X_test = scaler.transform(X_test)
X_test

array([[-1.2494057 , -1.7244706 , -1.2679282 , ..., -1.7185442 ,
         0.31255597, -0.15336135],
       [ 0.46474156, -1.8827232 ,  0.45389032, ...,  0.45138463,
        -0.58436686, -0.1369734 ],
       [-0.63377726, -0.2612085 , -0.6017387 , ..., -0.01786998,
         0.7904786 , -0.03645959],
       ...,
       [-0.3419833 , -0.72449845, -0.38588998, ..., -0.4878717 ,
         0.17998157, -0.80997765],
       [ 0.27021235, -0.09607564,  0.22436973, ..., -0.04476983,
        -1.0344648 , -0.80724627],
       [-0.2561614 ,  1.9657936 , -0.28853023, ..., -0.5292677 ,
        -0.7218513 , -1.0863904 ]], dtype=float32)

In [24]:
predict = tf.sigmoid(tf.matmul(X_test, w) + b)
predict

<tf.Tensor: id=257102, shape=(114, 1), dtype=float32, numpy=
array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
 

In [25]:
predict01 = tf.cast(predict > 0.5, dtype="float32")
print("="*30)
print("predict01")
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(114, 1), dtype=float32)


In [26]:
ac01 = tf.equal(predict01, y_test)
ac01

<tf.Tensor: id=257107, shape=(114, 1), dtype=bool, numpy=
array([[False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True]

In [27]:
ac02 = tf.cast(ac01, dtype="float32")
ac02

<tf.Tensor: id=257108, shape=(114, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
   

In [28]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=257110, shape=(), dtype=float32, numpy=0.32456142>

In [29]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype="float32"))
print("=" * 30)
print("accuracy")
print(accuracy.numpy())

accuracy
0.32456142
