In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.enable_eager_execution()
tf.__version__

'1.15.0'

In [3]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
], dtype="float32")

y = np.array([
    [0.],
    [0.],
    [0.],
    [1.]
], dtype="float32")

In [4]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [5]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [6]:
w = tf.Variable([[1], [2]], dtype="float32")
b = tf.Variable([3], dtype="float32")

In [7]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [8]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>

In [9]:
tf.matmul(X, w)

<tf.Tensor: id=21, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)>

In [10]:
tf.matmul(X, w) + b

<tf.Tensor: id=26, shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)>

In [11]:
tf.sigmoid(tf.matmul(X, w) + b)

<tf.Tensor: id=32, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)>

In [12]:
optimizer = tf.train.AdamOptimizer(0.01) # 뒤에 숫자는 learning rate다

In [13]:
for step in range(5000):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X, w) + b)
        cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1-y) * tf.log(1-hypothesis))
        grads = tape.gradient(cost, [w, b])
    optimizer.apply_gradients(grads_and_vars=zip(grads, [w, b]))
    
    if step % 100 == 0:
        print("=" * 50)
        print("step: {}, cost: {}, w: {}, b: {}".format(step, cost.numpy(), w.numpy(), b.numpy()))
        print("=" * 50)

step: 0, cost: 3.0189826488494873, w: [[0.99]
 [1.99]], b: [2.99]
step: 100, cost: 1.852928876876831, w: [[0.01112575]
 [1.001489  ]], b: [2.0029898]
step: 200, cost: 1.0872457027435303, w: [[-0.7114206 ]
 [ 0.18463652]], b: [1.1350006]
step: 300, cost: 0.8457093834877014, w: [[-0.7703851 ]
 [-0.11182875]], b: [0.5257181]
step: 400, cost: 0.7202606201171875, w: [[-0.45110112]
 [-0.03789832]], b: [0.06198942]
step: 500, cost: 0.6177883148193359, w: [[-0.07153893]
 [ 0.16270587]], b: [-0.35743272]
step: 600, cost: 0.5337925553321838, w: [[0.2775185 ]
 [0.39751324]], b: [-0.75495905]
step: 700, cost: 0.4659406244754791, w: [[0.58535916]
 [0.63830775]], b: [-1.1313305]
step: 800, cost: 0.41105538606643677, w: [[0.8586162]
 [0.8750349]], b: [-1.4864284]
step: 900, cost: 0.36615604162216187, w: [[1.1055079]
 [1.103506 ]], b: [-1.8219206]
step: 1000, cost: 0.32885342836380005, w: [[1.332784 ]
 [1.3223376]], b: [-2.1403058]
step: 1100, cost: 0.29735806584358215, w: [[1.5453968]
 [1.5316243]], 

In [14]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[7.0477467],
       [7.0392036]], dtype=float32)>

In [15]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-10.636643], dtype=float32)>

In [16]:
predict = tf.sigmoid(tf.matmul(X, w) + b)
predict

<tf.Tensor: id=315293, shape=(4, 1), dtype=float32, numpy=
array([[2.4018951e-05],
       [2.6663357e-02],
       [2.6885968e-02],
       [9.6924031e-01]], dtype=float32)>

In [17]:
predict01 = tf.cast(predict > 0.5, dtype="float32")
print("=" * 30)
print("predict01")
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]], shape=(4, 1), dtype=float32)


In [18]:
ac01 = tf.equal(predict01, y)
ac01

<tf.Tensor: id=315298, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [19]:
ac02 = tf.cast(ac01, dtype="float32")
ac02

<tf.Tensor: id=315299, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [20]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=315301, shape=(), dtype=float32, numpy=1.0>

In [21]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype="float32"))
print("=" * 30)
print("accuracy")
print(accuracy.numpy())

accuracy
1.0


In [24]:
arr = np.array([[1, 1]], dtype="float32")
predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict

<tf.Tensor: id=315321, shape=(1, 1), dtype=float32, numpy=array([[0.9692403]], dtype=float32)>

In [25]:
predict = tf.cast(predict > 0.5, dtype="float32")
predict.numpy()

array([[1.]], dtype=float32)

In [26]:
arr=np.array([[1,1]], dtype="float32")
predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict

<tf.Tensor: id=315330, shape=(1, 1), dtype=float32, numpy=array([[0.9692403]], dtype=float32)>

In [ ]:
predict = tf.cast(predict > 0.5, dtype="float32")
predict.numpy()