In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer()

sample_text = ["In digital circuits and machine learning, "
               "one-hot is a group of bits among which the legal combinations "
               "of values are only those with a single high bit and all the others low."]

In [5]:
vectorizer.fit(sample_text) # 소문자로도 바꾼다잉... 알아서 벡터화 함
# 해석하기 위해서는 수치화가 필요한데 이 수치화를 해주는 것이 워드벡터화

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [6]:
print(vectorizer.vocabulary_)

{'in': 12, 'digital': 8, 'circuits': 6, 'and': 2, 'machine': 17, 'learning': 14, 'one': 19, 'hot': 11, 'is': 13, 'group': 9, 'of': 18, 'bits': 5, 'among': 1, 'which': 26, 'the': 23, 'legal': 15, 'combinations': 7, 'values': 25, 'are': 3, 'only': 20, 'those': 24, 'with': 27, 'single': 22, 'high': 10, 'bit': 4, 'all': 0, 'others': 21, 'low': 16}


In [9]:
vector = vectorizer.transform(sample_text)

In [10]:
print(vector.toarray())

[[1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1]]


In [12]:
print(vectorizer.transform(['and', 'the']).toarray() )

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]]


In [14]:
sample_text2 = ['Today is the day that I do the thing today, today']

In [15]:
new_vectorizer = CountVectorizer()

In [16]:
train_data_structure = new_vectorizer.fit_transform(sample_text2)

In [19]:
print(train_data_structure.toarray())
print(new_vectorizer.vocabulary_) # 알파벳 순서로 먼저 와야 하는 순서로 숫자 배정... 왜 일곱개인가 : today는 중복이고 'I'는 무시되었다

[[1 1 1 1 2 1 3]]
{'today': 6, 'is': 2, 'the': 4, 'day': 0, 'that': 3, 'do': 1, 'thing': 5}


In [20]:
print(new_vectorizer.get_feature_names())

['day', 'do', 'is', 'that', 'the', 'thing', 'today']


In [21]:
print(train_data_structure) # 벡터 정보가 summary 되어 표출
# 반복된 횟수... today는 6번. 빈도수는 3
# 위치정보는 들어가있지 않다. 자연어 처리에는 부족. 빈도수만 알 수 있다

  (0, 6)	3
  (0, 2)	1
  (0, 4)	2
  (0, 0)	1
  (0, 3)	1
  (0, 1)	1
  (0, 5)	1
